### ISSUE TITLE
Mod branches source code moved to separate repositories. (Issue #22) 

### ISSUE THREAD

**Issue by sixcentgeorge** [malortie/hl-asheep#1]
i re-use the email title... i had in the gmail...

you should try to move all your "mods" to bots-united...and invite "official teams" to do the same...
like 

http://mods.davlevels.com/azuresheep/downloads/
https://www.moddb.com/mods/azure-sheep

http://www.bots-united.com/
http://forums.bots-united.com/

https://github.com/Bots-United

the steam hl is still getting updates....so the code of mods need changes to run...
i hope to get POV code...for my HLGianT....
with the Svencoop 3 and After Code source

have a cool day

**Comment by malortie** [comment]
There is no plan for me to get in contact with teams to move mods to specific forums.

Regarding POV mod, the mod has a lot of custom entities, so recreating it requires a considerable amount of work, along with retesting each feature present in the original mod.

I currently have no plan on recreating POV and I can't tell if and when I'll do it.

**Comment by sixcentgeorge** [comment]
except doing nothing ..or being like working but doing nothing.. i never seen you doing something..i admit we are are both french....  i recognize the famous cgt...workers..  as you are a " mobDB svencoooo p  & bms " teams member...  try to play latest "polishwicked" bms engine with AMD crossfire...!!!!
that is FUN... and of course : that can not PLAY IT !!!!!!

**Comment by sixcentgeorge** [comment]
FOR POV.. it has in its dll entities for map like the monsters in opposing force...
that would be great to do talks about hl and its mods ...bots in the "last" giant forum" dedicated to this game..and open it to the hl2..that will die soon... i am sure we can make hl3 that no one ASK ...

**Comment by malortie** [comment]
Regarding your [previous comment](https://github.com/malortie/hl-asheep/issues/1#issuecomment-981113177), please read the [code of conduct](https://github.com/malortie/hl-asheep/blob/58a402d5e1982b1b7b9476108d04856d0fdeb8b8/CODE_OF_CONDUCT.md#our-standards), and avoid using derogative comments in the future.

And regarding POV, this is out of scope of the current project, which is only for tracking issues with the Azure Sheep reimplementation.
